# Generated by Django 5.0.6 on 2024-07-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='otp_expiry',
        ),
    ]
